#pragma once

enum Error {
    OK,

    // generic
    FAILED,
    ERR_UNAVAILABLE,
    ERR_UNCONFIGURED,
    ERR_UNAUTHORIZED,
    ERR_INVALID_PARAMETER,
    ERR_INVALID_DATA,
    ERR_ALREADY_EXISTS,
    ERR_DOES_NOT_EXIST,
    ERR_TIMEOUT,
    ERR_BUSY,
    ERR_INTERRUPTED,
    ERR_CANT_CREATE,

    // memory
    ERR_OUT_OF_MEMORY,
    ERR_OUT_OF_VIDEO_MEMORY,
    ERR_MEMORY_LEAK,
    ERR_BUFFER_OVERFLOW,

    // file system
    ERR_FILE_NOT_FOUND,
    ERR_FILE_BAD_DRIVE,
    ERR_FILE_BAD_PATH,
    ERR_FILE_NO_PERMISSION,
    ERR_FILE_ALREADY_IN_USE,
    ERR_FILE_CANT_OPEN,
    ERR_FILE_CANT_CREATE,
    ERR_FILE_CANT_WRITE,
    ERR_FILE_CANT_READ,
    ERR_FILE_UNRECOGNIZED,
    ERR_FILE_CORRUPT,
    ERR_FILE_MISSING_DEPENDENCIES,
    ERR_FILE_EOF,

    // resource system
    ERR_RESOURCE_NOT_FOUND,
    ERR_RESOURCE_CORRUPT,
    ERR_RESOURCE_VERSION_MISMATCH,

    // link failed
    ERR_LINK_FAILED,

    ERR_MAX
};

extern const char *error_names[];
